# Generated by Django 6.0.5 on 2026-06-20 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gt', datetime.timedelta(0))), name='duration_positive', violation_error_message='Длительность должна быть положительной'),
        ),
    ]
