# Generated by Django 6.0.5 on 2026-09-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_non_negative', violation_error_message='Стоимость не может быть отрицательной'),
        ),
    ]
