# Generated by Django 6.0.5 on 2026-05-28 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, upload_to='masters/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('services', models.ManyToManyField(blank=True, related_name='masters', to='services.service', verbose_name='Услуги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_working', models.BooleanField(default=False, help_text='Если выключено — выходной. Если включено — особые часы.', verbose_name='Рабочий день')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало работы')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец работы')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Причина')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='masters.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Исключение в расписании',
                'verbose_name_plural': 'Исключения в расписании',
                'ordering': ['master', 'date'],
                'unique_together': {('master', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='masters.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Рабочее расписание',
                'verbose_name_plural': 'Рабочее расписание',
                'ordering': ['master', 'day_of_week'],
                'unique_together': {('master', 'day_of_week')},
            },
        ),
    ]
