# Generated by Django 6.0.5 on 2026-08-17 06:05

import apps.masters.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало работы')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец работы')),
                ('is_working', models.BooleanField(default=False, help_text='Если выключено — выходной. Если включено — особые часы.', verbose_name='Рабочий день')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Исключение в расписании',
                'verbose_name_plural': 'Исключения в расписании',
            },
            bases=(apps.masters.utils.WorkingHoursMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало работы')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец работы')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'Рабочее расписание',
                'verbose_name_plural': 'Рабочее расписание',
            },
            bases=(apps.masters.utils.WorkingHoursMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, upload_to='masters/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('services', models.ManyToManyField(blank=True, related_name='masters', to='services.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
