# Generated by Django 6.0.5 on 2026-08-17 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='masters.master', verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='masters.master', verbose_name='Мастер'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleexception',
            unique_together={('master', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('master', 'day_of_week')},
        ),
    ]
