# Generated by Django 6.0.5 on 2026-05-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='scheduleexception',
            options={'verbose_name': 'Исключение в расписании', 'verbose_name_plural': 'Исключения в расписании'},
        ),
        migrations.AlterField(
            model_name='scheduleexception',
            name='reason',
            field=models.CharField(blank=True, max_length=100, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало работы'),
        ),
    ]
