# Generated by Django 6.0.5 on 2026-09-18 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleexception',
            options={'ordering': ['master', '-date'], 'verbose_name': 'Исключение в расписании', 'verbose_name_plural': 'Исключения в расписании'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['master', 'day_of_week'], 'verbose_name': 'Рабочее расписание', 'verbose_name_plural': 'Рабочие расписания'},
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='День недели'),
        ),
    ]
