# Generated by Django 6.0.5 on 2026-06-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_master_options_alter_scheduleexception_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'Рабочее расписание', 'verbose_name_plural': 'Рабочее расписание'},
        ),
    ]
