# Generated by Django 6.0.5 on 2026-06-12 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0003_alter_workschedule_options'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Начало')),
                ('end_datetime', models.DateTimeField(editable=False, verbose_name='Конец')),
                ('status', models.CharField(choices=[('booked', 'Забронирована'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('no_show', 'Неявка')], default='booked', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='masters.master', verbose_name='Мастер')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-start_datetime'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('master', 'start_datetime'), name='unique_active_booking')],
            },
        ),
    ]
