# Generated by Django 6.0.5 on 2026-08-17 06:05

import apps.appointments.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Начало')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('status', models.CharField(choices=[('booked', 'Забронирована'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('no_show', 'Неявка')], default='booked', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-start_datetime'],
            },
            bases=(apps.appointments.utils.AppointmentValidationMixin, models.Model),
        ),
    ]
