# Generated by Django 6.0.5 on 2026-08-17 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('masters', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='masters.master', verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service', verbose_name='Услуга'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['master', 'start_datetime'], name='appointment_master__f0f7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'start_datetime'], name='appointment_client__f72115_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('master', 'start_datetime'), name='unique_active_booking', violation_error_message='Мастер уже занят в это время'),
        ),
    ]
