# Generated by Django 6.0.5 on 2026-06-20 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_client_alter_appointment_master_and_more'),
        ('masters', '0003_alter_workschedule_options'),
        ('services', '0002_service_duration_positive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AlterConstraint(
            model_name='appointment',
            name='unique_active_booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('master', 'start_datetime'), name='unique_active_booking', violation_error_message='Мастер уже занят в это время'),
        ),
    ]
