# Generated by Django 6.0.5 on 2026-10-03 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Конец'),
            preserve_default=False,
        ),
    ]
