# Generated by Django 6.0.5 on 2026-10-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(blank=True, verbose_name='Конец'),
        ),
    ]
